name: JQTesting

on: 
 push: 
    branches:
        - main

 jobs: 
    JQ Deployment:
        runs-on: ubuntu-latest
        steps:

        - name: checkout code
          uses: actions/checkout@v4       

        - name: run powershell
          shell: pwsh
          run: |
              local/customerdms-local.ps1


        - name: Update ACR Name in parameter file
        
        run: |
            jq '.parameters.acrName.value = env.acrName | .parameters.location.value = env.location | .parameters.acrSku.value = env.acrSku ' / 
                 ./environments/preproduction/local/parameters.json > "./parameters/parameters_updated.json"

