name: JQTesting

on: 
 push: 
    branches:
        - main

jobs: 
    JQDeployment:
        runs-on: ubuntu-latest
        steps:

        - name: checkout code
          uses: actions/checkout@v4       

        - name: run PowerShell
          shell: pwsh
          run: |
              local/customerdms-local.ps1


        - name: Update ACR Name in parameter file
        
          run: |
               jq '.parameters.acrName.value = env.acrName | .parameters.location.value = env.location | .parameters.acrSku.value = env.acrSku ' / 
                 ./local/parameters.json > ./local/parameters_updated.json

